networks:
    default: development
    development:
        max_fee: 500 gwei
        priority_fee: 1 gwei

compiler:
    solc:
        version: 0.8.11
        optimizer:
            enabled: true
            runs: 999999
